site_name: 'Docker Mailserver'
site_description: 'A fullstack but simple mail server (SMTP, IMAP, LDAP, Antispam, Antivirus, etc.) using Docker.'
site_author: 'docker-mailserver (Github Organization)'
repo_name: 'docker-mailserver'
repo_url: 'https://github.com/docker-mailserver/docker-mailserver'
copyright: '<p>&copy <a href="https://github.com/docker-mailserver"><em>Docker Mailserver Organization</em></a><br/><span>This project is licensed under the MIT license.</span></p>'
edit_uri: 'edit/master/docs/content'
docs_dir: 'content/'
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.expand

# plugins:
#   - search
#   - redirects:
#       redirect_maps:
#         tutorials/faq: config/troubleshooting/faq.md

markdown_extensions:
  - toc:
      permalink: ⚓︎
  - abbr
  - attr_list
  - admonition
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: yml
          lang: yaml
        - name: cf
          lang: cfg
        - name: conf
          lang: cfg
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# If referencing a file more than once, the URLs will all point to the nav hierarchy of the final file.
nav:
  - Home: index.md
  - 'An Introduction to Mail Servers': introduction.md
  - Configuration:
      - 'Your Best Friend setup.sh': config/setup.sh.md
      - 'User Management':
          - Accounts: config/user-management/accounts.md
          - Aliases: config/user-management/aliases.md
      - 'Best Practices':
          - DKIM: config/best-practices/dkim.md
          - DMARC: config/best-practices/dmarc.md
          - SPF: config/best-practices/spf.md
          - Auto-discovery: config/best-practices/autodiscover.md
      - Security:
          - 'Understanding the Ports': config/security/understanding-the-ports.md
          - 'SSL/TLS': config/security/ssl.md
          - Fail2Ban: config/security/fail2ban.md
      - Troubleshooting:
          - Debugging: config/troubleshooting/debugging.md
          - FAQ: config/troubleshooting/faq.md
      - 'Mail Delivery with POP3': config/pop3.md
  - Advanced:
      - 'Optional Configuration': advanced/optional-config.md
      - Maintenance:
          - 'Update and Cleanup': advanced/maintenance/update-and-cleanup.md
      - 'Override the Default Configs':
          - Dovecot: advanced/override-defaults/dovecot.md
          - Postfix: advanced/override-defaults/postfix.md
      - 'LDAP Authentication': advanced/auth-ldap.md
      - 'Email Filtering with Sieve': advanced/mail-sieve.md
      - 'Email Gathering with Fetchmail': advanced/mail-fetchmail.md
      - 'Email Forwarding':
          - 'Relay Hosts': advanced/mail-forwarding/relay-hosts.md
          - 'AWS SES': advanced/mail-forwarding/aws-ses.md
      - 'Full-Text Search': advanced/full-text-search.md
      - Kubernetes: advanced/kubernetes.md
      - IPv6: advanced/ipv6.md
  - Tutorials:
      - 'Installation Examples': tutorials/installation-examples.md
  - Use Cases:
      - 'Forward-Only Mailserver with LDAP': uses-cases/forward-only-mailserver-with-ldap-authentication.md
  - DockerHub: https://hub.docker.com/repository/docker/mailserver/docker-mailserver
  - GHCR: https://github.com/orgs/docker-mailserver/packages/container/package/docker-mailserver
