name: Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: mkdocs build --strict
      run: |
        docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict --config-file docs/mkdocs.yml
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    if: github.event_name != 'push'
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: mkdocs gh-pages --force
      run: |
        docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy --force --config-file docs/mkdocs.yml
